name: leader_pose_25_to_26
from_domain: 25
to_domain: 26

topics:
  /leader_pose:
    type: geometry_msgs/msg/PoseStamped
    qos:
      reliability: reliable
      durability: volatile
      history: keep_last
      depth: 10
