name: map_25_to_26_bridge_example
from_domain: 25
to_domain: 26

topics:
  /map:
    type: nav_msgs/msg/OccupancyGrid
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 1
