from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument('device', default_value='/dev/video1'),
        DeclareLaunchArgument('fallback_devices', default_value='/dev/video1,/dev/video0,/dev/video2,/dev/video3'),
        DeclareLaunchArgument('frame_id', default_value='camera_link'),
        DeclareLaunchArgument('width', default_value='1920'),
        DeclareLaunchArgument('height', default_value='1080'),
        DeclareLaunchArgument('send_width', default_value='1920'),
        DeclareLaunchArgument('send_height', default_value='1080'),
        DeclareLaunchArgument('camera_fps', default_value='30.0'),
        DeclareLaunchArgument('buffer_size', default_value='1'),
        DeclareLaunchArgument('fourcc', default_value='MJPG'),
        DeclareLaunchArgument('server_url', default_value='http://10.10.14.58:5005/detect'),
        DeclareLaunchArgument('output_topic', default_value='/risk/yolo_detections'),
        DeclareLaunchArgument('max_rate_hz', default_value='0.0'),
        DeclareLaunchArgument('http_worker_count', default_value='2'),
        DeclareLaunchArgument('jpeg_quality', default_value='85'),
        DeclareLaunchArgument('timeout_sec', default_value='0.8'),
        DeclareLaunchArgument('connect_timeout_sec', default_value='0.25'),
        DeclareLaunchArgument('read_timeout_sec', default_value='1.2'),
        DeclareLaunchArgument('max_http_roundtrip_sec', default_value='1.5'),
        DeclareLaunchArgument('max_frame_age_sec', default_value='1.5'),
        DeclareLaunchArgument('retry_open_period_sec', default_value='1.0'),
        DeclareLaunchArgument('publish_empty_detections', default_value='true'),
        DeclareLaunchArgument('enable_role_gating', default_value='false'),
        DeclareLaunchArgument('robot_name', default_value=''),
        DeclareLaunchArgument('boot_id', default_value=''),
        DeclareLaunchArgument('initial_role', default_value='ACTIVE_SCOUT'),
        DeclareLaunchArgument('role_topic', default_value=''),
        DeclareLaunchArgument('pose_topic', default_value='/member_pose'),
        DeclareLaunchArgument('require_capture_pose', default_value='true'),
        DeclareLaunchArgument('pose_history_duration_sec', default_value='8.0'),
        DeclareLaunchArgument('max_pose_interpolation_error_sec', default_value='0.35'),
        DeclareLaunchArgument('camera_hfov_deg', default_value='62.0'),
        DeclareLaunchArgument('camera_calibration_id', default_value=''),
        DeclareLaunchArgument('initial_role_active', default_value='true'),
        DeclareLaunchArgument('active_roles', default_value='ACTIVE_SCOUT,SCOUT,FOLLOWER,RECOVERING'),
        Node(
            package='flask_yolo_bridge',
            executable='opencv_camera_to_flask_yolo',
            name='opencv_camera_to_flask_yolo',
            output='screen',
            parameters=[{
                'device': LaunchConfiguration('device'),
                'fallback_devices': LaunchConfiguration('fallback_devices'),
                'frame_id': LaunchConfiguration('frame_id'),
                'width': LaunchConfiguration('width'),
                'height': LaunchConfiguration('height'),
                'send_width': LaunchConfiguration('send_width'),
                'send_height': LaunchConfiguration('send_height'),
                'camera_fps': LaunchConfiguration('camera_fps'),
                'buffer_size': LaunchConfiguration('buffer_size'),
                'fourcc': LaunchConfiguration('fourcc'),
                'server_url': LaunchConfiguration('server_url'),
                'output_topic': LaunchConfiguration('output_topic'),
                'max_rate_hz': LaunchConfiguration('max_rate_hz'),
                'http_worker_count': LaunchConfiguration('http_worker_count'),
                'jpeg_quality': LaunchConfiguration('jpeg_quality'),
                'timeout_sec': LaunchConfiguration('timeout_sec'),
                'connect_timeout_sec': LaunchConfiguration('connect_timeout_sec'),
                'read_timeout_sec': LaunchConfiguration('read_timeout_sec'),
                'max_http_roundtrip_sec': LaunchConfiguration('max_http_roundtrip_sec'),
                'max_frame_age_sec': LaunchConfiguration('max_frame_age_sec'),
                'retry_open_period_sec': LaunchConfiguration('retry_open_period_sec'),
                'publish_empty_detections': LaunchConfiguration('publish_empty_detections'),
                'enable_role_gating': LaunchConfiguration('enable_role_gating'),
                'robot_name': LaunchConfiguration('robot_name'),
                'boot_id': LaunchConfiguration('boot_id'),
                'initial_role': LaunchConfiguration('initial_role'),
                'role_topic': LaunchConfiguration('role_topic'),
                'pose_topic': LaunchConfiguration('pose_topic'),
                'require_capture_pose': LaunchConfiguration('require_capture_pose'),
                'pose_history_duration_sec': LaunchConfiguration('pose_history_duration_sec'),
                'max_pose_interpolation_error_sec': LaunchConfiguration('max_pose_interpolation_error_sec'),
                'camera_hfov_deg': LaunchConfiguration('camera_hfov_deg'),
                'camera_calibration_id': LaunchConfiguration('camera_calibration_id'),
                'initial_role_active': LaunchConfiguration('initial_role_active'),
                'active_roles': LaunchConfiguration('active_roles'),
            }],
        ),
    ])
