from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory
import os


def generate_launch_description():
    pkg_share = get_package_share_directory('tb3_bayesian_risk_map')
    default_config = os.path.join(pkg_share, 'config', 'bayesian_risk_map.yaml')

    return LaunchDescription([
        DeclareLaunchArgument('config_file', default_value=default_config),
        DeclareLaunchArgument('use_sim_time', default_value='false'),
        DeclareLaunchArgument('map_topic', default_value='/map'),
        DeclareLaunchArgument('image_topic', default_value='/camera/image_raw'),
        DeclareLaunchArgument('map_frame', default_value='map'),
        DeclareLaunchArgument('base_frame', default_value='base_link'),
        DeclareLaunchArgument('pose_history_duration_sec', default_value='5.0'),
        DeclareLaunchArgument('pose_history_max_error_sec', default_value='0.75'),
        DeclareLaunchArgument('detection_source', default_value='local_yolo'),
        DeclareLaunchArgument('external_detection_topic', default_value='/risk/yolo_detections'),
        DeclareLaunchArgument('debug_image_topic', default_value='/risk/debug_yolo_image'),
        DeclareLaunchArgument('enable_yolo', default_value='true'),
        DeclareLaunchArgument('enable_fake_detection', default_value='false'),
        DeclareLaunchArgument('model_path', default_value='yolo11n.pt'),
        DeclareLaunchArgument('device', default_value='cpu'),
        DeclareLaunchArgument('update_rate_hz', default_value='2.0'),
        DeclareLaunchArgument('conf_threshold', default_value='0.20'),
        DeclareLaunchArgument('yolo_max_rate_hz', default_value='3.0'),
        DeclareLaunchArgument('opencv_camera_device', default_value='/dev/video0'),
        DeclareLaunchArgument('opencv_camera_width', default_value='640'),
        DeclareLaunchArgument('opencv_camera_height', default_value='480'),
        DeclareLaunchArgument('opencv_camera_fps', default_value='15.0'),
        DeclareLaunchArgument('publish_overlay', default_value='true'),
        DeclareLaunchArgument('publish_debug_image', default_value='true'),
        DeclareLaunchArgument('publish_debug_compressed_image', default_value='false'),
        DeclareLaunchArgument('debug_compressed_image_topic', default_value='/risk/debug_yolo_image/compressed'),
        DeclareLaunchArgument('debug_compressed_jpeg_quality', default_value='70'),
        DeclareLaunchArgument('debug_show_opencv', default_value='false'),
        DeclareLaunchArgument('debug_save_images', default_value='false'),
        DeclareLaunchArgument('preserve_risk_on_map_resize', default_value='true'),
        DeclareLaunchArgument('source_halo_radius_m', default_value='0.75'),
        DeclareLaunchArgument('source_halo_sigma_m', default_value='0.35'),
        DeclareLaunchArgument('enable_room_probability', default_value='true'),
        DeclareLaunchArgument('enable_region_segmentation', default_value='true'),
        DeclareLaunchArgument('enable_visibility_tracking', default_value='true'),
        DeclareLaunchArgument('diagnostic_publish_rate_hz', default_value='1.0'),

        Node(
            package='tb3_bayesian_risk_map',
            executable='bayesian_risk_map_node',
            name='bayesian_risk_map_node',
            output='screen',
            parameters=[
                LaunchConfiguration('config_file'),
                {
                    'use_sim_time': LaunchConfiguration('use_sim_time'),
                    'map_topic': LaunchConfiguration('map_topic'),
                    'image_topic': LaunchConfiguration('image_topic'),
                    'map_frame': LaunchConfiguration('map_frame'),
                    'base_frame': LaunchConfiguration('base_frame'),
                    'pose_history_duration_sec': LaunchConfiguration('pose_history_duration_sec'),
                    'pose_history_max_error_sec': LaunchConfiguration('pose_history_max_error_sec'),
                    'detection_source': LaunchConfiguration('detection_source'),
                    'external_detection_topic': LaunchConfiguration('external_detection_topic'),
                    'debug_image_topic': LaunchConfiguration('debug_image_topic'),
                    'enable_yolo': LaunchConfiguration('enable_yolo'),
                    'enable_fake_detection': LaunchConfiguration('enable_fake_detection'),
                    'model_path': LaunchConfiguration('model_path'),
                    'device': LaunchConfiguration('device'),
                    'update_rate_hz': LaunchConfiguration('update_rate_hz'),
                    'conf_threshold': LaunchConfiguration('conf_threshold'),
                    'yolo_max_rate_hz': LaunchConfiguration('yolo_max_rate_hz'),
                    'opencv_camera_device': LaunchConfiguration('opencv_camera_device'),
                    'opencv_camera_width': LaunchConfiguration('opencv_camera_width'),
                    'opencv_camera_height': LaunchConfiguration('opencv_camera_height'),
                    'opencv_camera_fps': LaunchConfiguration('opencv_camera_fps'),
                    'publish_overlay': LaunchConfiguration('publish_overlay'),
                    'publish_debug_image': LaunchConfiguration('publish_debug_image'),
                    'publish_debug_compressed_image': LaunchConfiguration('publish_debug_compressed_image'),
                    'debug_compressed_image_topic': LaunchConfiguration('debug_compressed_image_topic'),
                    'debug_compressed_jpeg_quality': LaunchConfiguration('debug_compressed_jpeg_quality'),
                    'debug_show_opencv': LaunchConfiguration('debug_show_opencv'),
                    'debug_save_images': LaunchConfiguration('debug_save_images'),
                    'preserve_risk_on_map_resize': LaunchConfiguration('preserve_risk_on_map_resize'),
                    'source_halo_radius_m': LaunchConfiguration('source_halo_radius_m'),
                    'source_halo_sigma_m': LaunchConfiguration('source_halo_sigma_m'),
                    'enable_room_probability': LaunchConfiguration('enable_room_probability'),
                    'enable_region_segmentation': LaunchConfiguration('enable_region_segmentation'),
                    'enable_visibility_tracking': LaunchConfiguration('enable_visibility_tracking'),
                    'diagnostic_publish_rate_hz': LaunchConfiguration('diagnostic_publish_rate_hz'),
                },
            ],
        ),
    ])
