leader:
  robot_name: leader
  domain_id: 20

field_robots:
  - robot_name: scout22
    domain_id: 22
    initial_role: ACTIVE_SCOUT
    map_capable: true
    camera_capable: true

  - robot_name: follower21
    domain_id: 21
    initial_role: FOLLOWER
    map_capable: true
    camera_capable: true
