fleet_commander_node:
  ros__parameters:
    robot_names: [waffle, burger]
    spacing: 0.85
    frame_id: map
    formation_type: column
    republish_count: 3
    republish_period_sec: 0.10

fleet_state_echo:
  ros__parameters:
    robot_names: [waffle, burger]
    print_period_sec: 2.0
