from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    use_sim_time = LaunchConfiguration('use_sim_time')
    map_topic = LaunchConfiguration('map_topic')
    region_map_topic = LaunchConfiguration('region_map_topic')
    scan_topic = LaunchConfiguration('scan_topic')
    global_frame = LaunchConfiguration('global_frame')
    robot_frame = LaunchConfiguration('robot_frame')
    auto_start = LaunchConfiguration('auto_start')

    return LaunchDescription([
        DeclareLaunchArgument('use_sim_time', default_value='true'),
        DeclareLaunchArgument('map_topic', default_value='/map'),
        DeclareLaunchArgument('region_map_topic', default_value='/slam_region_graph/region_map'),
        DeclareLaunchArgument('scan_topic', default_value='/scan'),
        DeclareLaunchArgument('global_frame', default_value='map'),
        DeclareLaunchArgument('robot_frame', default_value='base_footprint'),
        DeclareLaunchArgument('auto_start', default_value='true'),
        DeclareLaunchArgument('timer_period_sec', default_value='0.05'),
        DeclareLaunchArgument('planning_period_sec', default_value='0.35'),
        DeclareLaunchArgument('goal_dispatch_period_sec', default_value='0.10'),
        DeclareLaunchArgument('min_goal_interval_sec', default_value='0.05'),
        DeclareLaunchArgument('rolling_goal_update_enabled', default_value='true'),
        DeclareLaunchArgument('rolling_goal_period_sec', default_value='0.12'),
        DeclareLaunchArgument('rolling_goal_near_distance_m', default_value='1.15'),
        DeclareLaunchArgument('rolling_goal_min_shift_m', default_value='0.12'),
        DeclareLaunchArgument('rolling_goal_min_score_improvement', default_value='0.50'),
        DeclareLaunchArgument('rolling_goal_ignore_scan_turn', default_value='true'),
        DeclareLaunchArgument('dynamic_timer_period_update', default_value='true'),
        DeclareLaunchArgument('rolling_goal_force_period_sec', default_value='0.55'),
        DeclareLaunchArgument('rolling_goal_force_near_distance_m', default_value='1.35'),
        DeclareLaunchArgument('rolling_goal_yaw_change_rad', default_value='0.45'),
        DeclareLaunchArgument('rolling_goal_reason_change_min_shift_m', default_value='0.08'),
        DeclareLaunchArgument('rolling_goal_preempt_cooldown_sec', default_value='0.10'),
        DeclareLaunchArgument('rolling_goal_debug_throttle_sec', default_value='0.75'),
        DeclareLaunchArgument('coverage_update_period_sec', default_value='0.10'),
        DeclareLaunchArgument('coverage_publish_period_sec', default_value='0.10'),
        DeclareLaunchArgument('coverage_interpolate_motion_enabled', default_value='true'),
        DeclareLaunchArgument('coverage_motion_sample_step_m', default_value='0.04'),
        DeclareLaunchArgument('coverage_motion_yaw_step_deg', default_value='3.0'),
        DeclareLaunchArgument('coverage_motion_max_gap_m', default_value='0.80'),
        DeclareLaunchArgument('coverage_motion_max_samples', default_value='32'),
        DeclareLaunchArgument('coverage_live_debug_throttle_sec', default_value='1.0'),
        DeclareLaunchArgument('candidate_priority_queue_enabled', default_value='true'),
        DeclareLaunchArgument('candidate_queue_size', default_value='30'),
        DeclareLaunchArgument('candidate_queue_refresh_period_sec', default_value='0.80'),
        DeclareLaunchArgument('candidate_queue_revalidate_period_sec', default_value='0.05'),
        DeclareLaunchArgument('candidate_queue_max_age_sec', default_value='8.0'),
        DeclareLaunchArgument('candidate_queue_min_score', default_value='1.0'),
        DeclareLaunchArgument('candidate_queue_include_global_frontier', default_value='true'),
        DeclareLaunchArgument('candidate_queue_include_next_region', default_value='true'),
        DeclareLaunchArgument('candidate_queue_log_throttle_sec', default_value='0.75'),
        DeclareLaunchArgument('map_expand_lidar_push_enabled', default_value='true'),
        DeclareLaunchArgument('map_expand_push_into_lidar_clear_unknown', default_value='true'),
        DeclareLaunchArgument('map_expand_goal_push_max_m', default_value='1.20'),
        DeclareLaunchArgument('map_expand_unknown_push_max_m', default_value='0.55'),
        DeclareLaunchArgument('map_expand_goal_push_step_m', default_value='0.10'),
        DeclareLaunchArgument('map_expand_goal_push_min_m', default_value='0.25'),
        DeclareLaunchArgument('map_expand_goal_push_lidar_margin_m', default_value='0.28'),
        DeclareLaunchArgument('map_expand_goal_push_score_bonus_per_m', default_value='10.0'),
        DeclareLaunchArgument('lidar_push_log_throttle_sec', default_value='1.0'),
        DeclareLaunchArgument('coverage_front_only', default_value='true'),
        DeclareLaunchArgument('coverage_fov_deg', default_value='55.0'),
        DeclareLaunchArgument('coverage_max_range_m', default_value='1.45'),
        DeclareLaunchArgument('coverage_brush_radius_m', default_value='0.06'),
        DeclareLaunchArgument('coverage_ray_step_m', default_value='0.025'),
        DeclareLaunchArgument('coverage_downsample_angle_step_deg', default_value='1.0'),
        DeclareLaunchArgument('coverage_only_known_free', default_value='true'),
        DeclareLaunchArgument('coverage_stop_at_unknown', default_value='true'),
        DeclareLaunchArgument('coverage_require_lidar_clear', default_value='true'),
        DeclareLaunchArgument('coverage_obstacle_margin_m', default_value='0.12'),
        DeclareLaunchArgument('candidate_grid_step_m', default_value='0.25'),
        DeclareLaunchArgument('candidate_min_clearance_m', default_value='0.22'),
        DeclareLaunchArgument('candidate_max_goal_distance_m', default_value='5.0'),
        DeclareLaunchArgument('candidate_max_count', default_value='120'),
        DeclareLaunchArgument('frontier_candidate_sampling', default_value='true'),
        DeclareLaunchArgument('frontier_candidate_max_count', default_value='120'),
        DeclareLaunchArgument('scan_turn_yaw_step_deg', default_value='135.0'),
        DeclareLaunchArgument('allow_cross_region_view_gain', default_value='true'),
        DeclareLaunchArgument('view_fov_deg', default_value='80.0'),
        DeclareLaunchArgument('view_max_range_m', default_value='2.4'),
        DeclareLaunchArgument('w_region_coverage_gain', default_value='4.0'),
        DeclareLaunchArgument('w_region_frontier_gain', default_value='3.0'),
        DeclareLaunchArgument('w_cross_region_unknown', default_value='1.5'),
        DeclareLaunchArgument('w_cross_region_frontier', default_value='1.0'),
        DeclareLaunchArgument('w_candidate_distance_cost', default_value='2.5'),
        DeclareLaunchArgument('w_candidate_distance_sq_cost', default_value='0.45'),
        DeclareLaunchArgument('w_candidate_obstacle_density_cost', default_value='180.0'),
        DeclareLaunchArgument('w_candidate_unknown_density_cost', default_value='30.0'),
        DeclareLaunchArgument('w_candidate_clearance_risk_cost', default_value='45.0'),
        DeclareLaunchArgument('candidate_obstacle_line_step_m', default_value='0.05'),
        DeclareLaunchArgument('candidate_obstacle_check_radius_m', default_value='0.18'),
        DeclareLaunchArgument('region_coverage_threshold', default_value='0.86'),
        DeclareLaunchArgument('region_frontier_threshold', default_value='8'),
        DeclareLaunchArgument('region_candidate_gain_threshold', default_value='18.0'),
        DeclareLaunchArgument('region_map_gain_threshold', default_value='14.0'),
        DeclareLaunchArgument('region_coverage_gain_threshold', default_value='12.0'),
        DeclareLaunchArgument('region_min_active_time_sec', default_value='15.0'),
        DeclareLaunchArgument('region_max_active_time_sec', default_value='55.0'),
        DeclareLaunchArgument('region_switch_on_stall', default_value='true'),
        DeclareLaunchArgument('region_switch_gain_ratio', default_value='0.65'),
        DeclareLaunchArgument('region_switch_coverage_ratio', default_value='0.72'),
        DeclareLaunchArgument('prefer_unvisited_region', default_value='true'),
        DeclareLaunchArgument('nav2_goal_timeout_sec', default_value='45.0'),
        DeclareLaunchArgument('goal_blacklist_radius_m', default_value='0.70'),
        DeclareLaunchArgument('goal_blacklist_time_sec', default_value='60.0'),
        DeclareLaunchArgument('allow_nav2_scan_turn_goal', default_value='true'),
        DeclareLaunchArgument('allow_nav2_forward_probe_goal', default_value='true'),
        DeclareLaunchArgument('forward_probe_distance_m', default_value='0.55'),
        DeclareLaunchArgument('forward_probe_min_distance_m', default_value='0.28'),
        DeclareLaunchArgument('forward_probe_lidar_margin_m', default_value='0.18'),

        Node(
            package='tb3_region_mapper',
            executable='region_nav2_explorer_node',
            name='region_nav2_explorer',
            output='screen',
            parameters=[{
                'use_sim_time': use_sim_time,
                'map_topic': map_topic,
                'region_map_topic': region_map_topic,
                'scan_topic': scan_topic,
                'global_frame': global_frame,
                'robot_frame': robot_frame,
                'auto_start': auto_start,
                'timer_period_sec': LaunchConfiguration('timer_period_sec'),
                'planning_period_sec': LaunchConfiguration('planning_period_sec'),
                'goal_dispatch_period_sec': LaunchConfiguration('goal_dispatch_period_sec'),
                'min_goal_interval_sec': LaunchConfiguration('min_goal_interval_sec'),
                'rolling_goal_update_enabled': LaunchConfiguration('rolling_goal_update_enabled'),
                'rolling_goal_period_sec': LaunchConfiguration('rolling_goal_period_sec'),
                'rolling_goal_near_distance_m': LaunchConfiguration('rolling_goal_near_distance_m'),
                'rolling_goal_min_shift_m': LaunchConfiguration('rolling_goal_min_shift_m'),
                'rolling_goal_min_score_improvement': LaunchConfiguration('rolling_goal_min_score_improvement'),
                'rolling_goal_ignore_scan_turn': LaunchConfiguration('rolling_goal_ignore_scan_turn'),
                'dynamic_timer_period_update': LaunchConfiguration('dynamic_timer_period_update'),
                'rolling_goal_force_period_sec': LaunchConfiguration('rolling_goal_force_period_sec'),
                'rolling_goal_force_near_distance_m': LaunchConfiguration('rolling_goal_force_near_distance_m'),
                'rolling_goal_yaw_change_rad': LaunchConfiguration('rolling_goal_yaw_change_rad'),
                'rolling_goal_reason_change_min_shift_m': LaunchConfiguration('rolling_goal_reason_change_min_shift_m'),
                'rolling_goal_preempt_cooldown_sec': LaunchConfiguration('rolling_goal_preempt_cooldown_sec'),
                'rolling_goal_debug_throttle_sec': LaunchConfiguration('rolling_goal_debug_throttle_sec'),
                'coverage_update_period_sec': LaunchConfiguration('coverage_update_period_sec'),
                'coverage_publish_period_sec': LaunchConfiguration('coverage_publish_period_sec'),
                'coverage_interpolate_motion_enabled': LaunchConfiguration('coverage_interpolate_motion_enabled'),
                'coverage_motion_sample_step_m': LaunchConfiguration('coverage_motion_sample_step_m'),
                'coverage_motion_yaw_step_deg': LaunchConfiguration('coverage_motion_yaw_step_deg'),
                'coverage_motion_max_gap_m': LaunchConfiguration('coverage_motion_max_gap_m'),
                'coverage_motion_max_samples': LaunchConfiguration('coverage_motion_max_samples'),
                'coverage_live_debug_throttle_sec': LaunchConfiguration('coverage_live_debug_throttle_sec'),
                'candidate_priority_queue_enabled': LaunchConfiguration('candidate_priority_queue_enabled'),
                'candidate_queue_size': LaunchConfiguration('candidate_queue_size'),
                'candidate_queue_refresh_period_sec': LaunchConfiguration('candidate_queue_refresh_period_sec'),
                'candidate_queue_revalidate_period_sec': LaunchConfiguration('candidate_queue_revalidate_period_sec'),
                'candidate_queue_max_age_sec': LaunchConfiguration('candidate_queue_max_age_sec'),
                'candidate_queue_min_score': LaunchConfiguration('candidate_queue_min_score'),
                'candidate_queue_include_global_frontier': LaunchConfiguration('candidate_queue_include_global_frontier'),
                'candidate_queue_include_next_region': LaunchConfiguration('candidate_queue_include_next_region'),
                'candidate_queue_log_throttle_sec': LaunchConfiguration('candidate_queue_log_throttle_sec'),
                'map_expand_lidar_push_enabled': LaunchConfiguration('map_expand_lidar_push_enabled'),
                'map_expand_push_into_lidar_clear_unknown': LaunchConfiguration('map_expand_push_into_lidar_clear_unknown'),
                'map_expand_goal_push_max_m': LaunchConfiguration('map_expand_goal_push_max_m'),
                'map_expand_unknown_push_max_m': LaunchConfiguration('map_expand_unknown_push_max_m'),
                'map_expand_goal_push_step_m': LaunchConfiguration('map_expand_goal_push_step_m'),
                'map_expand_goal_push_min_m': LaunchConfiguration('map_expand_goal_push_min_m'),
                'map_expand_goal_push_lidar_margin_m': LaunchConfiguration('map_expand_goal_push_lidar_margin_m'),
                'map_expand_goal_push_score_bonus_per_m': LaunchConfiguration('map_expand_goal_push_score_bonus_per_m'),
                'lidar_push_log_throttle_sec': LaunchConfiguration('lidar_push_log_throttle_sec'),
                'coverage_front_only': LaunchConfiguration('coverage_front_only'),
                'coverage_fov_deg': LaunchConfiguration('coverage_fov_deg'),
                'coverage_max_range_m': LaunchConfiguration('coverage_max_range_m'),
                'coverage_brush_radius_m': LaunchConfiguration('coverage_brush_radius_m'),
                'coverage_ray_step_m': LaunchConfiguration('coverage_ray_step_m'),
                'coverage_downsample_angle_step_deg': LaunchConfiguration('coverage_downsample_angle_step_deg'),
                'coverage_only_known_free': LaunchConfiguration('coverage_only_known_free'),
                'coverage_stop_at_unknown': LaunchConfiguration('coverage_stop_at_unknown'),
                'coverage_require_lidar_clear': LaunchConfiguration('coverage_require_lidar_clear'),
                'coverage_obstacle_margin_m': LaunchConfiguration('coverage_obstacle_margin_m'),
                'candidate_grid_step_m': LaunchConfiguration('candidate_grid_step_m'),
                'candidate_min_clearance_m': LaunchConfiguration('candidate_min_clearance_m'),
                'candidate_max_goal_distance_m': LaunchConfiguration('candidate_max_goal_distance_m'),
                'candidate_max_count': LaunchConfiguration('candidate_max_count'),
                'frontier_candidate_sampling': LaunchConfiguration('frontier_candidate_sampling'),
                'frontier_candidate_max_count': LaunchConfiguration('frontier_candidate_max_count'),
                'allow_cross_region_view_gain': LaunchConfiguration('allow_cross_region_view_gain'),
                'view_fov_deg': LaunchConfiguration('view_fov_deg'),
                'view_max_range_m': LaunchConfiguration('view_max_range_m'),
                'w_region_coverage_gain': LaunchConfiguration('w_region_coverage_gain'),
                'w_region_frontier_gain': LaunchConfiguration('w_region_frontier_gain'),
                'w_cross_region_unknown': LaunchConfiguration('w_cross_region_unknown'),
                'w_cross_region_frontier': LaunchConfiguration('w_cross_region_frontier'),
                'w_candidate_distance_cost': LaunchConfiguration('w_candidate_distance_cost'),
                'w_candidate_distance_sq_cost': LaunchConfiguration('w_candidate_distance_sq_cost'),
                'w_candidate_obstacle_density_cost': LaunchConfiguration('w_candidate_obstacle_density_cost'),
                'w_candidate_unknown_density_cost': LaunchConfiguration('w_candidate_unknown_density_cost'),
                'w_candidate_clearance_risk_cost': LaunchConfiguration('w_candidate_clearance_risk_cost'),
                'candidate_obstacle_line_step_m': LaunchConfiguration('candidate_obstacle_line_step_m'),
                'candidate_obstacle_check_radius_m': LaunchConfiguration('candidate_obstacle_check_radius_m'),
                'region_coverage_threshold': LaunchConfiguration('region_coverage_threshold'),
                'region_frontier_threshold': LaunchConfiguration('region_frontier_threshold'),
                'region_candidate_gain_threshold': LaunchConfiguration('region_candidate_gain_threshold'),
                'region_map_gain_threshold': LaunchConfiguration('region_map_gain_threshold'),
                'region_coverage_gain_threshold': LaunchConfiguration('region_coverage_gain_threshold'),
                'region_min_active_time_sec': LaunchConfiguration('region_min_active_time_sec'),
                'region_max_active_time_sec': LaunchConfiguration('region_max_active_time_sec'),
                'region_switch_on_stall': LaunchConfiguration('region_switch_on_stall'),
                'region_switch_gain_ratio': LaunchConfiguration('region_switch_gain_ratio'),
                'region_switch_coverage_ratio': LaunchConfiguration('region_switch_coverage_ratio'),
                'prefer_unvisited_region': LaunchConfiguration('prefer_unvisited_region'),
                'nav2_goal_timeout_sec': LaunchConfiguration('nav2_goal_timeout_sec'),
                'goal_blacklist_radius_m': LaunchConfiguration('goal_blacklist_radius_m'),
                'goal_blacklist_time_sec': LaunchConfiguration('goal_blacklist_time_sec'),
                'allow_nav2_scan_turn_goal': LaunchConfiguration('allow_nav2_scan_turn_goal'),
                'scan_turn_yaw_step_deg': LaunchConfiguration('scan_turn_yaw_step_deg'),
                'allow_nav2_forward_probe_goal': LaunchConfiguration('allow_nav2_forward_probe_goal'),
                'forward_probe_distance_m': LaunchConfiguration('forward_probe_distance_m'),
                'forward_probe_min_distance_m': LaunchConfiguration('forward_probe_min_distance_m'),
                'forward_probe_lidar_margin_m': LaunchConfiguration('forward_probe_lidar_margin_m'),
            }],
        ),
    ])
